### ISSUE TITLE
Documentation roadmap

### ISSUE THREAD

**Issue by susliko** [TinkoffCreditSystems/tofu#263]
The goal of this issue is to track an overall progress over `tofu` documentation.
I propose the following structure:

## Core
- [x] Error management (split into `Raise`, `Handle/Restore` pages?)
- [x] Forking and racing (split into `Fire`, `Race`, `Start` pages?)
- [ ] Execute
- [ ] Guarantee
- [ ] Timeout
- [ ] Void

## Contextual
- [x] Env
- [x] Context (rename page from `HasContext` to `Context`?)

## Concurrent
- [x] Agent
- [ ] Atom
- [ ] Daemon
- [ ] GateKeeper
- [ ] ReadWrite
- [ ] QVar
- [ ] MakeDeferred
- [ ] MakeMVar
- [x] MakeRef
- [ ] MakeSemaphore

## Optics
- [x] Hierarchy (redraw the hierarchy?)
- [ ] Contains
- [ ] Equivalent
- [ ] Extract
- [ ] Folded
- [ ] Items
- [ ] Property
- [ ] Subset
- [ ] Updated

## Utilities
- [x] Config
- [x] Console
- [x] Logging
- [x] Memo

Any comments are highly appreciated!

**Comment by susliko** [comment]
@Odomontois @catostrophe @danslapman

**Comment by hellboy81** [comment]
Ready to write documentation
